spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ororderdb
    username: admin 
    password: password
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  profiles:
    active: spring.profiles.active
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
        ddl-auto: none
  application:
    name: Order-Service
  messages:
    basename: messages
    encoding: UTF-8
    use-code-as-default-message: true
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com.project.ordermanagement: DEBUG
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
